name: mychain  

on:
  workflow_dispatch:
    inputs:
      run-job-3:
        description: "Run job 3?"
        required: true
        type: boolean
jobs:
  job-1:
    name: job 1
    runs-on: ubuntu-latest
    steps:
      - name: Output for job 1
        run: echo `job1 running, are we running job 3 , ${{ github.event.inputs.run-job-3 }}`

  job-2:
     name: job2
     runs-on: ubuntu-latest
     needs: 
       - job-1
     steps:
       - name: output for job 2
         run: echo "job 2 running"

  job-3: 
     name: job3
     if: github.events.input.run-job-3 == true
     runs-on: ubuntu-latest
     steps:
       - name: output for job 3
         run: echo "job 3 running"
       
      
